server:
  port: 8084
spring:
  application:
    name: sky-report
  profiles:
    active: local
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:192.168.6.128:8848}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: default
      paths-to-match: /**
      packages-to-scan: com.sky.controller

knife4j:
  enable: true
  setting:
    language: zh_cn