sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.6.128
    port: 3306
    database: sky_trade         # 关键：只连自己的库
    username: root
    password: 123
  redis:
    host: 192.168.6.128
    port: 6379
    password:
    database: 0
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    map-underscore-to-camel-case: true
