
sky:
    jwt:
        admin-secret-key: itcast
        admin-ttl: 720000000
        admin-token-name: token
        user-secret-key: itheima
        user-ttl: 7200000
        user-token-name: authentication